### ISSUE TITLE
Create Figma Prototype

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#1]
### Sub-tasks:
- [x] Design homepage
- [x] Design Venue listing
- [x] Design individual venue pages (with booking options)
- [x] Design booking form
- [ ] Design admin dashboard for managing bookings
- [x] Design user login/sign-up pages
