### ISSUE TITLE
Develop Customer-Facing Pages

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#3]
### Sub-tasks:
- [x] Create homepage (venue listing)
- [x] Add venue filters (location, price, availability)
- [x] Create individual venue pages
- [x] Style and layout adjustments (responsiveness)
