### ISSUE TITLE
Implement Booking System

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#4]
### Sub-tasks:
- [x] Implement booking form (date picker, user info)
- [x] Validate form inputs
- [x] Set up state management (context API/Redux)
