### ISSUE TITLE
Create Admin Dashboard

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#5]
### Sub-tasks:
- [x] Create admin login page
- [x] Display list of all bookings
- [x] Implement venue management (create, update, delete)
