### ISSUE TITLE
Set Up Authentication

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#6]
### Sub-tasks:
- [x] Implement user sign-up
- [x] Implement user login (with JWT or token-based authentication)
- [x] Restrict access to admin dashboard
