### ISSUE TITLE
Set Up API Integration

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#7]
### Sub-tasks:
- [x] Set up API to fetch venues and bookings
- [x] Implement POST/GET requests for bookings
- [x] Ensure data is persisted in the database/mock backend
