### ISSUE TITLE
Design Refinement and Testing

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#8]
### Sub-tasks:
- [x] Check and fix layout issues (desktop and mobile)
- [x] Fine-tune color schemes, typography
- [x] Test booking process (select venue, confirm booking)
- [x] Test admin functionality (delete bookings, manage venues)
- [x] Test login/authentication flow
- [x] Fix bugs based on testing results
