### ISSUE TITLE
Final Review and Submission

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-two#9]
### Sub-tasks:
- [x] Clean up code (remove unused components, variables)
- [x] Ensure code is well-commented
- [x] Deploy final version to GitHub Pages/Netlify
- [x] Prepare and submit project deliverables
